from __future__ import annotations

from enum import Enum


class MutationType(str, Enum):
    STRUCTURE_INVALID = "STRUCTURE_INVALID"
    SCHEMA_MISSING_FIELD = "SCHEMA_MISSING_FIELD"
    SCHEMA_TYPE_MISMATCH = "SCHEMA_TYPE_MISMATCH"
    FORMAT_VIOLATION = "FORMAT_VIOLATION"
    VALUE_OUT_OF_RANGE = "VALUE_OUT_OF_RANGE"
    ENUM_VIOLATION = "ENUM_VIOLATION"
    ADDITIONAL_FIELD = "ADDITIONAL_FIELD"
    AUTH_MISSING = "AUTH_MISSING"
    AUTH_INVALID = "AUTH_INVALID"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"
    RATE_LIMIT = "RATE_LIMIT"
    RATE_LIMIT_INFORMATIONAL = "RATE_LIMIT_INFORMATIONAL"
    WRONG_CONTENT_TYPE = "WRONG_CONTENT_TYPE"


MUTATION_EXPECTATIONS: dict[MutationType, list[int]] = {
    MutationType.STRUCTURE_INVALID: [400],
    MutationType.SCHEMA_MISSING_FIELD: [400, 422],
    MutationType.SCHEMA_TYPE_MISMATCH: [400, 422],
    MutationType.FORMAT_VIOLATION: [400, 422],
    MutationType.VALUE_OUT_OF_RANGE: [400, 422],
    MutationType.ENUM_VIOLATION: [400, 422],
    MutationType.ADDITIONAL_FIELD: [400, 422],
    MutationType.AUTH_MISSING: [401, 403],
    MutationType.AUTH_INVALID: [401],
    MutationType.PERMISSION_DENIED: [403],
    MutationType.METHOD_NOT_ALLOWED: [405, 404],
    MutationType.RESOURCE_NOT_FOUND: [404],
    MutationType.DUPLICATE_RESOURCE: [409],
    MutationType.RATE_LIMIT: [429],
    MutationType.RATE_LIMIT_INFORMATIONAL: [429],
    MutationType.WRONG_CONTENT_TYPE: [400, 415, 422],
}


class FailureReason(str, Enum):
    INFRA_ERROR = "INFRA_ERROR"
    SERVER_ERROR = "SERVER_ERROR"
    ACCEPTED_INVALID_INPUT = "ACCEPTED_INVALID_INPUT"
    WRONG_REJECTION_CODE = "WRONG_REJECTION_CODE"
    RATE_LIMIT_NOT_ENFORCED = "RATE_LIMIT_NOT_ENFORCED"
