"""
Auth Helper — JWT injection and header management for negative tests.

Provides utilities to:
  - Build Authorization headers from a JWT token
  - Inject auth into test cases that require it
  - Identify public routes that should skip auth
  - Prepare complete request headers respecting test-case overrides
"""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .session_manager import NegativeTestSessionManager

from .execution_context import TokenMutator


# Routes that never require authentication
_PUBLIC_ROUTES: set[str] = {
    "/auth/login",
    "/auth/signup",
    "/auth/verify",
    "/auth/reset",
    "/auth/forgot-password",
    "/health",
    "/docs",
    "/openapi.json",
    "/redoc",
}


def build_auth_headers(token: str) -> dict[str, str]:
    """
    Build an Authorization header dict from a JWT token.

    Args:
        token: The JWT token string.

    Returns:
        Dict with the ``Authorization: Bearer <token>`` header,
        or empty dict if token is falsy.
    """
    if not token:
        return {}
    return {"Authorization": f"Bearer {token}"}


def is_public_route(path: str) -> bool:
    """
    Check whether a given path is a public (unauthenticated) route.

    Performs a prefix match so that ``/auth/login`` matches
    ``/auth/login#some-fragment`` or ``/auth/login?query=1``.

    Args:
        path: The endpoint path to check.

    Returns:
        True if the path matches a known public route.
    """
    # Strip fragments and query params for matching
    clean = path.split("?")[0].split("#")[0]

    return clean in _PUBLIC_ROUTES


def inject_auth(test_case: dict, token: str) -> dict:
    """
    Inject authentication headers into a test case if it requires auth.

    Rules:
      - If ``needs_auth`` is ``True``, adds the Bearer token header.
      - If ``needs_auth`` is ``False`` (e.g. auth_failure tests), skips.
      - If ``custom_headers`` is present, those take precedence.

    Args:
        test_case: A negative test case dict (as generated by the engines).
        token: The JWT token to inject.

    Returns:
        The test case dict with headers updated (mutated in place and returned).
    """
    needs_auth = test_case.get("needs_auth", False)

    if not needs_auth:
        return test_case

    # Don't override custom_headers if already set (e.g. auth_failure tests
    # that deliberately set invalid Authorization headers)
    if "custom_headers" in test_case and test_case["custom_headers"]:
        return test_case

    # Inject the valid token
    if "custom_headers" not in test_case:
        test_case["custom_headers"] = {}

    test_case["custom_headers"].update(build_auth_headers(token))
    return test_case


def prepare_request_headers(
    test_case: dict,
    session: "NegativeTestSessionManager",
) -> dict[str, str]:
    """
    Build the complete set of HTTP headers for executing a test case.

    This is the primary entry point for the test runner. It handles:
      1. Base headers (User-Agent)
      2. Auth injection (if ``needs_auth=True`` and no custom override)
      3. Custom header overrides from the test case
      4. Content-Type overrides (``force_content_type``)

    Args:
        test_case: A negative test case dict.
        session: The active session manager holding the JWT.

    Returns:
        Complete headers dict ready for the HTTP request.
    """
    headers: dict[str, str] = {
        "User-Agent": "Cognitest-Negative-Tester",
    }

    # Determine whether to inject auth
    needs_auth = test_case.get("needs_auth", False)
    auth_type = str(test_case.get("auth_type") or "").strip().lower()
    custom_headers = test_case.get("custom_headers")
    endpoint_path = test_case.get("endpoint_path", "")

    if needs_auth and not is_public_route(endpoint_path):
        # Auth-failure cases are handled explicitly by auth_type.
        if auth_type == "missing":
            pass
        elif auth_type == "invalid":
            headers["Authorization"] = TokenMutator.malformed()["Authorization"]
        elif auth_type == "expired":
            headers["Authorization"] = TokenMutator.expired()["Authorization"]
        # Only inject if no custom Authorization header is set
        elif not custom_headers or "Authorization" not in custom_headers:
            headers.update(build_auth_headers(session.token))

    # Apply custom headers (may override auth for tests like auth_failures)
    if custom_headers:
        headers.update(custom_headers)

    # Handle forced Content-Type
    force_ct = test_case.get("force_content_type")
    if force_ct == "__OMIT__":
        headers.pop("Content-Type", None)
    elif force_ct:
        headers["Content-Type"] = force_ct

    return headers
